# -*- coding: utf-8 -*-
"""Tp-Infra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ikDJKFeBY7mWKPK7pC2wnwyG47Ol3vdE
"""

pip install unidecode

import csv
import numpy as np
import pandas as pd
import random as rd
import string as st
from geopy.geocoders import Nominatim
from google.colab import drive
from datetime import datetime
from datetime import timedelta
import google.cloud.storage as storage
from google.colab import drive
import os
from unidecode import unidecode

drive.mount('/content/drive')
path = '/content/drive/MyDrive/Infra/TP_Final_Especificacion_1.xlsx'
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/content/drive/MyDrive/Infra/usm-infra-grupo8-401213-e5007b825f93.json"
storage_client = storage.Client()
bucket_name = "grupo_8_bucket"
bucket = storage_client.get_bucket(bucket_name)

def remove_accents_list(input_list):
  return [tuple(unidecode(x) if isinstance(x, str) else x for x in tup) for tup in input_list]

df_sheets_desc = pd.read_excel(path, sheet_name=None)
df_cond_vta = df_sheets_desc['Condicion_Venta']
df_unidades = df_sheets_desc['Unidades']
df_tipo_negocio = df_sheets_desc['Tipo_Negocio']
df_cadena = df_sheets_desc['Cadena']
df_dias_visita = df_sheets_desc['Dias_Visita']
df_productos = df_sheets_desc['Productos']
df_cond_venta = df_sheets_desc['Condicion_Venta']
df_localidades = df_sheets_desc['Prov_Localidades']
df_estado = df_sheets_desc['Estado_cliente']
df_dias_visita = df_sheets_desc['Dias_Visita']

def generar_codigos_sku(productos):
  codigos_sku = {}
  for producto in productos:
    caracteres = st.ascii_uppercase + st.digits
    sku_codigo = ''.join(rd.choice(caracteres) for _ in range(10))
    codigos_sku[producto] = sku_codigo
  return codigos_sku

codigos_sku = generar_codigos_sku(df_productos['nombre'])

columns_v = df_sheets_desc['Desc_Ventas']['Campo']
columns_s = df_sheets_desc['Desc_Stock']['Campo']
columns_m = df_sheets_desc['Desc_Clientes']['Campo']
columns_d = df_sheets_desc['Desc_Deuda']['Campo']

cant_dias = 90

fecha_actual = datetime.now()

cant_dist = 5

cant_clientes = 4

cant_sucursales = 5

for distribuidor in range(1, cant_dist + 1):

    for d in range(0, cant_dias):

        # Fecha de cierre
        fech_cierre = fecha_actual - timedelta(days=d)
        fech_cierre_string = f'{fech_cierre.year}-{fech_cierre.month:02d}-{fech_cierre.day:02d}'
        fech_cie_com_data = [fech_cierre_string for _ in range(cant_clientes)]

        # Generamos los datos de venta unidades
        vta_unidades_data = [(rd.randint(0, 100)) for _ in range(cant_clientes)]

        # Generamos los datos de venta en importes
        vta_importe_data = [round((rd.uniform(100, 1000)), 2) for _ in range(cant_clientes)]

        # Generamos la condición de venta
        cond_vta_data = [rd.choice(df_cond_vta['codigo_condicion']) for _ in range(cant_clientes)]

        codigo_sucursal_base = (distribuidor * 100)  # Código base para el distribuidor

        # Sucursales del distribuidor
        sucursales_dist = [(codigo_sucursal_base + rd.randint(10, 99)) for _ in range(cant_clientes)]

        # Clientes de la sucursal del distribuidor
        clientes = [(codigo_sucursal_base + rd.randint(1000, 9999)) for _ in range(cant_clientes)]

        # Provincia y ciudades
        provincias = [(rd.choice(df_localidades.columns.values)) for _ in range(cant_clientes)]
        ciudades_aleatorias = []

        for _ in range(cant_clientes):
            for p in provincias:
                ciudades_provincia = df_localidades[p].dropna().tolist()
                ciudad_aleatoria = rd.choice(ciudades_provincia)
                ciudades_aleatorias.append(ciudad_aleatoria)

        # Estado
        estado = [(rd.choices(df_estado['nombre'], weights=df_estado['probabilidades'], k=1)[0]) for _ in range(cant_clientes)]

        # Nombre del cliente
        nombre_cliente = [(f'Cliente_{_}') for _ in range(cant_clientes)]

        # CUIT
        cuit = [(rd.randint(10000000, 99999999)) for _ in range(cant_clientes)]

        # Razón Social
        razon_social = [(f"Empresa_{_}") for _ in range(cant_clientes)]

        # Dirección
        direccion = [(f"Direccion_{_}") for _ in range(cant_clientes)]

        # Días de visita
        dias_visita = [(rd.choice(df_dias_visita['codigo_dia'])) for _ in range(cant_clientes)]

        # Teléfono
        telefono = [(f"{rd.randint(100, 999)}-{rd.randint(100, 999)}-{rd.randint(1000, 9999)}") for _ in range(cant_clientes)]

        # Fecha de alta y de baja
        fecha_alta = []
        fecha_baja = []

        for i in range(cant_clientes):

            # Generar una fecha de alta anterior a la fecha actual
            fecha_alta_datetime = fecha_actual - timedelta(days=rd.randint(1, 365))
            fecha_alta.append(fecha_alta_datetime.strftime('%Y-%m-%d %H:%M:%S'))

            if estado[i] == 'I':
                # Generar una fecha de baja posterior a la fecha de alta pero anterior a la fecha actual
                fecha_baja_datetime = fecha_alta_datetime + timedelta(days=rd.randint(1, 365))
                fecha_baja.append(fecha_baja_datetime.strftime('%Y-%m-%d %H:%M:%S'))
            else:
                fecha_baja.append('-')  # Dejar fecha de baja vacía para clientes activos


        # Coordenadas
        geolocator = Nominatim(user_agent="nombre_de_usuario")


        coordenada_latitud = []
        coordenada_longitud = []


        for ciudad in ciudades_aleatorias:
            location = geolocator.geocode(ciudad)
            if location:
                coordenada_latitud.append(location.latitude)
                coordenada_longitud.append(location.longitude)
            else:
                coordenada_latitud.append(None)
                coordenada_longitud.append(None)


        # Tipo de negocio
        tipo_negocio = [(rd.choice(df_tipo_negocio['nombre'])) for _ in range(cant_clientes)]

        # ARCHIVO STOCK
        # Unidad
        unidad = [(rd.choice(df_unidades['codigo_unidad'])) for _ in range(cant_clientes)]

        # Stock
        stock = [(rd.randint(100, 500) if unidad == "UNI" else rd.randint(1, 100)) for _ in range(cant_clientes)]

        # Producto
        producto = []
        producto1 = []
        producto1 = list(codigos_sku.keys())
        producto1.extend(producto1)
        producto = producto1

        # SKU
        sku_codigo = []
        sku_codigo1 = []
        sku_codigo1 = list(codigos_sku.values())
        sku_codigo1.extend(sku_codigo1)
        sku_codigo = sku_codigo1

        # DEUDA
        deuda_vencida = [(round(rd.uniform(0, 1000), 2)) for _ in range(cant_clientes)]
        deuda_total = [(round(rd.uniform(0, 10000), 2)) for _ in range(cant_clientes)]

        # Data frame con data
        venta_clientes_data = list(zip(sucursales_dist, clientes, fech_cie_com_data, sku_codigo, vta_unidades_data, vta_importe_data, cond_vta_data))
        venta_clientes_data_list = remove_accents_list(venta_clientes_data)
        stock_data = list(zip(sucursales_dist, fech_cie_com_data, sku_codigo, producto, stock, unidad))
        stock_data_list = remove_accents_list(stock_data)
        clientes_data = list(zip(sucursales_dist, clientes, ciudades_aleatorias, provincias, estado, nombre_cliente, cuit, razon_social, direccion, dias_visita, telefono, fecha_alta, fecha_baja, coordenada_latitud, coordenada_longitud, cond_vta_data, deuda_vencida, tipo_negocio))
        clientes_data_list = remove_accents_list(clientes_data)
        deuda_data = list(zip(sucursales_dist, clientes, fech_cie_com_data, deuda_vencida, deuda_total))
        deuda_data_list = remove_accents_list(deuda_data)

        df_vta_cli = pd.DataFrame(venta_clientes_data_list,columns=columns_v)
        df_stock = pd.DataFrame(stock_data_list, columns=columns_s)
        df_clientes = pd.DataFrame(clientes_data_list, columns=columns_m)
        df_deuda = pd.DataFrame(deuda_data_list, columns=columns_d)

        # Subir archivos
        blob_v = bucket.blob("distribuidor_" + str(distribuidor) + "/venta_" + fech_cierre_string + ".csv")
        blob_v.upload_from_string(df_vta_cli.to_csv(index=False, encoding="utf-8"), content_type="text/csv")

        blob_s = bucket.blob("distribuidor_" + str(distribuidor) + "/stock_" + fech_cierre_string + ".csv")
        blob_s.upload_from_string(df_stock.to_csv(index=False, encoding="utf-8"), content_type="text/csv")

        blob_c = bucket.blob("distribuidor_" + str(distribuidor) + "/cliente_" + fech_cierre_string + ".csv")
        blob_c.upload_from_string(df_clientes.to_csv(index=False, encoding="utf-8"), content_type="text/csv")

        blob_d = bucket.blob("distribuidor_" + str(distribuidor) + "/deuda_" + fech_cierre_string + ".csv")
        blob_d.upload_from_string(df_deuda.to_csv(index=False, encoding="utf-8"), content_type="text/csv")